### ISSUE TITLE
CLI Roadmap

### ISSUE THREAD

**Issue by Graeme22** [tastyware/tastytrade-cli#12]
Hello all! Since this project has begun to pick up a bit of traction, I thought I'd list some of the priorities for this project towards an initial release hopefully by mid-2025 (as project is currently in beta).

Here's the main functionality I'd like to include, in addition to existing functionality:

- [x] Switch to `typer` instead of `click` as the main dependency. `typer` is supposed to get async support soon, so at that point we can move over.
- [x] `order` subcommand with support for order history as well as live orders, which can be replaced or cancelled. (In progress!)
- [x] `plot` subcommand which uses `gnuplot` and `py-gnuplot` (as an additional, optional dependency) to plot candle charts directly in the terminal. Would require terminals supporting the kitty graphics protocol, so kitty, ghostty, etc.
- [x] `watchlist` subcommand (maybe shortened to `wl`?) which can be used to scan through and filter watchlists for interesting trades.

Once we have those things, I think we can go ahead with a v1.0 release, hopefully after getting some people to test it as well! Then, further down the road we can consider some extra, fancier features:

- gamma exposure/gamma flip calculations and charting
- trade recommendations engine
- paper trading system
- full functionality backtesting system
- auto-trading system with a DSL

Some of these latter things are admittedly pretty ambitious, so they'd probably require some generous donations or potentially a subscription model, but they could be looked at if there were enough interest!

I'm open to any suggestions or thoughts, so this is in no way a list that's set in stone. PRs for new functionality or improvements are always welcome!

**Comment by theglove44** [comment]
Hi, I've stumbled on this from some Google Foo. I'm in the process of trying to build out using Python as script to work with the YTD transactions CSV from my portal.

I've been trying to get it to analyse the output and tag trades per strategy and then calculate and output a P&L per strategy and per Underlying Symbol. 

I'm finding it tricky to get the P&L bit to work with the various actions on trades with multi legs and adjustments.

Is this a feature that you'd look to put in as well?

**Comment by Graeme22** [comment]
> Hi, I've stumbled on this from some Google Foo. I'm in the process of trying to build out using Python as script to work with the YTD transactions CSV from my portal.
> 
> I've been trying to get it to analyse the output and tag trades per strategy and then calculate and output a P&L per strategy and per Underlying Symbol. 
> 
> I'm finding it tricky to get the P&L bit to work with the various actions on trades with multi legs and adjustments.
> 
> Is this a feature that you'd look to put in as well?

Potentially. I do have code for that kind of thing around somewhere, but it's never easy to do because Tasty doesn't actually have a concept of a trade as a unit--that is, opening, 0 or more rolls, then closing. So unlikely that will be in the CLI anytime soon.

**Comment by Kripta-Studios** [comment]
Hello, 
you python SDK for Tastytrade is really great. I've used it to create a Discord Bot that plots the greeks exposure on chart using matplot and all the data that I fetch using you SDK. I really appreciate all the work you're doing. 

I see that on your Roadmap you have:

- gamma exposure/gamma flip calculations and charting

In this repository [Option-Greeks-Plotting-Discord-Bot](https://github.com/Kripta-Studios/Option-Greeks-Plotting-Discord-Bot) I pretty much did exactly that. This an image of how it looks:

<img width="1619" height="953" alt="Image" src="https://github.com/user-attachments/assets/c361f2c2-1ef2-4e08-8e0b-e60c0d202272" />

<img width="1006" height="1548" alt="Image" src="https://github.com/user-attachments/assets/a75cd1ab-ddc5-4a32-84d6-c906a4983b45" />


The code is quite messy, like a bodge, I'm a new CS student, so clearly I'm still learning, I plan to improve the code. But maybe it can be helpful to your project and roadmap. I have already forked this repo, and I could try to create a pull request to combine my code with yours so you can have that GEX calculations and gamma flip on your wonderful CLI app. 

I'm also planning to use your SDK code to create a Tastytrade SDK written on Java (I have to learn it well for my classes) and then on C# to be able to use Tastytrade's options data on my Ninja Trader indicator (that broker uses C#).

I'm happy to help, learn, and gain experience.

**Comment by Graeme22** [comment]
That would be great! You could add it under the `plot` subcommand and draw the chart in the terminal using gnuplot. I actually have some old code for gamma calculations lying around, I will add you to the repo
